[[tasks]]
description = "Learn Python"
priority = 3
time_logged = 6.25
is_complete = false
tags = [ "edu", "dev",]

[[tasks]]
description = "Do exercises"
priority = 2
time_logged = 2
is_complete = true

